### PR TITLE
Fix building API server, kubeconfig URLs when kubeconfig secret is missing

### LINKED ISSUE #1836: [BUG] Erroneous API server, kubeconfig URLs building during instance deprovisioning
**Description**

The broker throws errors on GET instance requests when the instance is being deprovisioned:
```
"while getting APIServerURL: secret not found for runtime id <RUNTIME_ID>"
```
```
"while building kubeconfig, error: secret not found for runtime id <RUNTIME_ID>"
```

Automatic workflows handling instances can produce a lot of errors.

**Expected result**

Skip URLs building when the instance is being deprovisioned or log info regarding the missing kubeconfig secret instead of errors.

**Actual result**

Errors when the kubeconfig secret is missing due to instance deprovisioning.

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by szwedm**
**Description**

Changes proposed in this pull request:

- log INFO instead of ERROR when kubeconfig secret is missing
- do not add API server URL to labels when the value is empty

**Related issue(s)**

Fixes #1836

### CODE REVIEW

File: internal/broker/response_labels.go [hunk 1]
```diff
@@ -35,12 +36,14 @@ func ResponseLabels(op internal.ProvisioningOperation, instance internal.Instanc
 	if enableKubeconfigLabel && !IsOwnClusterPlan(instance.ServicePlanID) {
 		responseLabels[kubeconfigURLKey] = fmt.Sprintf("https://%s/kubeconfig/%s", brokerURL, instance.InstanceID)
 		apiServerUrl, err := kubeconfigBuilder.GetServerURL(instance.RuntimeID)
-		if err != nil {
-			slog.Error(fmt.Sprintf("while getting APIServerURL: %s", err))
-			return responseLabels
+		switch {
+		case err == nil && apiServerUrl != "":
```
Comment (jaroslaw-pieszka) [inline internal/broker/response_labels.go:40]: Should we check `apiServerUrl` or `apiServerUrlKey`?

Comment (szwedm) [reply internal/broker/response_labels.go:40]: `apiServerUrl`, its value justifies the existence in the map.

**Review by jaroslaw-pieszka — APPROVED** [review]
